days_id = {
    "monday": "AgACAgIAAxkBAANzZuLFR_zQnZFQYPGvDcxB7u_ROGwAAlbnMRsxXxhLV1-VNab958cBAAMCAAN5AAM2BA",
    "tuesday": "AgACAgIAAxkBAANyZuLFR2-OkMhgxwAB1oeBuFgkX79GAAJY5zEbMV8YS7a_t8TgXQ9LAQADAgADeQADNgQ",
    "wednesday": "AgACAgIAAxkBAANxZuLFRzojfLCwNvT4Pbgjnk9k70MAAlrnMRsxXxhLUOGwk-n3SZwBAAMCAAN5AAM2BA",
    "thursday": "AgACAgIAAxkBAANwZuLFR-RiFIThphn2NtiyCQVH-P4AAlfnMRsxXxhLLnpHrpXpgkgBAAMCAAN5AAM2BA",
    "friday": "AgACAgIAAxkBAAOEZuLGrZPgSPqou8kBrQR4iB1gKygAAmbnMRsxXxhLbqYRcg3-DwkBAAMCAAN5AAM2BA",
    "saturday":"AgACAgIAAxkBAAOaZuLNc0JBa7nx_BZmakWnr8MlfLYAAprnMRsxXxhLwhie8z8YMMUBAAMCAAN5AAM2BA",
    "the week" : "AgACAgIAAxkBAAOOZuLJgh8Z8Lq3-DtkfnsVWQ7oWq8AAnXnMRsxXxhLnKiofySbbrwBAAMCAAN5AAM2BA"
}

